# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa7930370b805722f04b47691ba405121ef59e8a12c80486190b8d38bc661c5b5ea592563c4f0a6e3c7ec3a4d8a09717e870c44ad24f538e470b3b0e7c8f0c29

test:
  secret_key_base: e34b58e8d3702fde010dc840bde660186c0737269c524ccf32fdb139e18a72ae6b1875b012b6bb1a23dbaca582b36a62b66aa3980615f0ea49684f6adc62451a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
